name: Code Quality

on:
  pull_request:
  push:
    branches:
      - main
    tags-ignore:
      - '*'

jobs:
  scan:
    name: Static Analysis with SonarCloud

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup PHP with Xdebug
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: xdebug

      - name: Install dependencies with composer
        run: composer install --no-ansi --no-interaction --no-progress && composer require barryvdh/laravel-debugbar spatie/laravel-typescript-transformer --dev

      - name: Run tests with pest
        run: vendor/bin/pest --coverage-clover coverage.xml

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse --memory-limit=-1 --error-format=json > phpstan.json

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  phpstan:
    name: Static Anaylsis with PHPStan

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup PHP with Xdebug
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: xdebug

      - name: Install dependencies with composer
        run: composer install --no-ansi --no-interaction --no-progress && composer require barryvdh/laravel-debugbar spatie/laravel-typescript-transformer --dev

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse --memory-limit=-1

  types:
    name: Type Coverage

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup PHP with Xdebug
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: xdebug

      - name: Install dependencies with composer
        run: composer install --no-ansi --no-interaction --no-progress

      - name: Run type coverage with pest
        run: vendor/bin/pest --type-coverage --min=98 --memory-limit=-1
