name: SonarCloud

on:
  pull_request:
  push:
    branches:
      - main
    tags-ignore:
      - '*'

jobs:
  scan:
    name: SonarCloud Scan

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup PHP with Xdebug
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: xdebug

      - name: Install dependencies with composer
        run: composer update --no-ansi --no-interaction --no-progress

      - name: Run tests with phpunit/phpunit
        run: >
          vendor/bin/phpunit --coverage-clover=coverage.xml
          


      - name: Run PHPStan
        run: vendor/bin/phpstan analyse --memory-limit=-1 --error-format=json > phpstan.json

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
