name: Tests

on:
  pull_request:
  push:
    branches:
      - main
    tags-ignore:
      - '*'

jobs:
  tests:
    name: Tests

    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        php-versions: [ '8.2', '8.3', '8.4' ]
        ignore-platform-reqs: [ '--ignore-platform-reqs', '' ]
        exclude:
          - php-versions: '8.4'
            ignore-platform-reqs: ''
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup PHP with Xdebug
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: xdebug
          extensions: mbstring, intl, fileinfo, sqlite3, pdo_sqlite

      - name: Install dependencies with composer
        run: composer update --no-ansi --no-interaction --no-progress ${{ matrix.ignore-platform-reqs }}

      - name: Run tests with pest
        run: vendor/bin/pest --coverage --min=80

      - name: Run type coverage with pest
        run: vendor/bin/pest --type-coverage --min=99 --memory-limit=-1
